Library_application/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include

urlpatterns = [
    path('',include('Users.urls')),
    path('lib/',include('hope.urls')),
    path('admin/', admin.site.urls),
    
    
    
]

hope/urls.py
from operator import index
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'hope'

urlpatterns = [
    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.logout,name='logout'),
    path('books/',views.index,name='index'),
    # <str:category>, passing the parameter from the template
    path('books/category/<str:category>/list', views.books_by_category, name='books_by_category'),
    path('book/<int:id>/Borrow',views.Borrow,name='Borrowpage'),
    path('book/borrow', views.borrow_book, name='borrow_book'),
    path('my/books', views.student_borrowed_books, name="student_borrowed_books"),
    path('books/unpicked',views.unpicked,name="unpicked_borrowed_books"),
    path('notification/',views.send_notification,name="send_notification"),
   
   
]

urlpatterns += staticfiles_urlpatterns()

hope/models.py
#from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User



# Create your models here.


class Books(models.Model):
    #extending from the inbuilt model TextChoices.
    class BookStatusChoices(models.TextChoices):
        AVAILABLE = "AV", ("Available")
        UNAVAILABLE = "UNAV", ("Unavailable")
        BOOKED = "BK", ("Booked")

    title = models.CharField( max_length=50)
    author = models.CharField(max_length=50)
    copy_number = models.IntegerField()
    subject_area  = models.CharField(max_length=50)
    publication_date = models.DateField()
    status = models.CharField(max_length=20, default="AV", choices=BookStatusChoices.choices)
    category = models.CharField(max_length=100, default="Engineering")
    
   

class Borrowed_books(models.Model):
    
    class ReturnStatusChoices(models.TextChoices):
        BOOKED = "BK", ("Booked")
        TAKEN = "TK", ("Taken")
        RETURNED = "RT", ("Returned")
        
    book = models.ForeignKey(Books,related_name= 'titles', on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name = 'first_names',on_delete = models.CASCADE,max_length=100)
    pickup_date = models.DateTimeField(null=True)
    return_date = models.DateTimeField(null=True)
    fine = models.IntegerField(null=True, blank=True)
    return_status = models.CharField(max_length=15, default="BK", choices=ReturnStatusChoices.choices)

    
    

hope/views.py
import email
from urllib import request
from django.shortcuts import render,redirect
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from django.contrib.auth.models import User,auth
from django.contrib import messages
from django.contrib.auth import logout
from django.urls import reverse
from .models import Books, Borrowed_books
from datetime import datetime
from django.core.mail import send_mail




# Create your views here.
def login(request):
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect(request.build_absolute_uri('/lib/books'))
        
        messages.info(request,'invalid username or password')
        return redirect(request.build_absolute_uri('/lib/login'))
    # if request is GET
    else: 
        return render(request,'login.html')

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        first_name = request.POST['first_name']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        last_name =  request.POST['last_name']
        if password1!=password2:
            messages.info(request,'Password not matching') 
            return redirect(request.build_absolute_uri('/lib/register'))
        if User.objects.filter(username=username).exists():
            messages.info(request,'Username taken')
            return redirect(request.build_absolute_uri('/lib/register'))
        elif User.objects.filter(email=email).exists():
            messages.info(request,'Email taken')
            return redirect(request.build_absolute_uri('/lib/register'))
        else:
            user = User.objects.create_user(
                username=username,email=email,
                password=password1,first_name=first_name,last_name=last_name)
            user.save()
            return redirect('/')
            # add message
        
              
        
    else:
        return render(request,'register.html')

def logout(request):
    auth.logout(request)
    return redirect(request.build_absolute_uri('/lib/login'))

def books_categories():
    """
        Get the categories of books
    """
    return Books.objects.only('category').distinct('category') 

def index(request):
    books = Books.objects.all().order_by('title')
    categories = books_categories() # call for categories
    return render(request,'hope/index.html',
        {'books':books, 'categories': categories, 'title': 'ALL Books'}
    )


def books_by_category(request, category):
    """
        View books for each category
    """
    # call for categories, used in the template navigation bar.
    categories = books_categories()
    books = Books.objects.filter(category=category)
    return render(request,'hope/books_by_category.html',
        {'books':books, 'categories': categories, 'title': f"Book in {category.upper()}"}
    )

def Borrow(request,id):
    book = Books.objects.get(id=id)
    
    categories = books_categories()

    return render(request,'hope/borrow_book.html',{
        'book': book,
        'categories': categories,
        'book_id': id,
        'title': 'Borrow a Book'
    })

def borrow_book(request):
   
    if request.method != "POST":
        return HttpResponseBadRequest({'message': 'Bad Request'})
    
    # get user id
    user_id = request.user.id
    book = Books.objects.get(id=request.POST.get('book_id'))
    if book.status == 'AV':
        book.status = 'UNAV'
        book.save()
    book_id = request.POST.get('book_id')
    book = Books.objects.get(id=book_id)
    user = User.objects.get(id=user_id) 

    borrowed_book = Borrowed_books.objects.create(book=book,
    user=user,pickup_date=datetime.now(),fine=0)
    borrowed_book.save()

    

    return redirect(request.build_absolute_uri('/lib/my/books'))


def student_borrowed_books(request):
    
    books = Borrowed_books.objects.filter(user_id=request.user.id).select_related()
    #select_related fetches other details about the book
        
    return render(request,'hope/borrowed_books.html',{
        'books': books,
        'categories':books_categories() ,
        'title': 'My Borrow Book'
    })



def update_books_availability(book_id):
    """
        Make a book available for booking.
    """
    book = Books.objects.get(id=book_id)
    # make a book available for booking
    book.status = 'AV'
    book.save()

def delete_unpicked_booked_books(book_id):
    """
        Delete Unpicked Books From Borrowed Books records
    """
    # get unpicked book after the grace period
    book = Borrowed_books.objects.filter(id=book_id)
    # delete the record since book was never picked
    book.delete()

def unpicked_booked_books():
    """
     Unpicked Books
    """
    #fetch all unpicked books
    books = Borrowed_books.objects.filter(return_status='BK')
    
    #if the books objects is empty, return response
    if not books.count():
        return 0 # return an http response
    else: 
        #looping through the returned objects(books)
        updated_books = 0

        for book in books:
            # strftime converts datetime object to string
            diff = datetime.now() - datetime.strptime(datetime.strftime(book.pickup_date,"%Y-%m-%d %H:%M:%S:%f"),"%Y-%m-%d %H:%M:%S:%f")

            #check the diffence in minutes
            if diff.total_seconds()/60 > 60:
                 #call the 2nd function to make a book available
                update_books_availability(book_id=book.book_id)
                # call the 3rd function to the delete the related record from borrowed books
                delete_unpicked_booked_books(book_id=book.id)
                updated_books += 1
                #book_id = id where id is the primary key for the books...or the id of that specific book
        return updated_books

def unpicked(request):
    unpicked_books = unpicked_booked_books()
    mss = "No unpicked books available"
    if unpicked_books:
        mss = f"{unpicked_books} have been made available for booking"
    
    messages.info(request, mss)

    return render(request,'unpicked.html', {"categories": books_categories()})


def send_notification(request):
    if request.method == "POST":
        sub = request.POST.get('subject')
        msg = request.POST.get('message')
        e_mail = request.POST.get('e_mail')
        
        send_mail(
            sub,msg,'aina.isaac@gmail.com',[e_mail]
        )
        return HttpResponse('Email sent')
    return render(request,'notification.html')

hope/templates/hope/app.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>HOPE-LIBRARY | {{ title }}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a href="#" class="navbar-brand">
                HOPE-LIBRARY
            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav">
                    <h5 class="text-success">Click on the category to search for the required book</h5>
                    <a href="{% url 'hope:index' %}" class="nav-item nav-link active">ALL</a>
                    {% for category in categories %}
                        <a href="{% url 'hope:books_by_category' category.category %}" 
                        class="nav-item nav-link"> {{ category.category }}</a>
                    {% endfor %}
                </div>
                <div class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                        {% if user.is_superuser %}
                            <a href="/admin" class="nav-item nav-link text-primary">Admin Panel </a>
                            <a href="/lib/notification" class="nav-item nav-link text-primary">Send Notification</a>
                            <a href="{% url 'hope:unpicked_borrowed_books' %}" class="nav-item nav-link text-success">(Make Unpicked Books Available)</a>
                        {% else %} 
                            <a href="{% url 'hope:student_borrowed_books' %}" class="nav-item nav-link">My Books</a>
                        {% endif %}
                        <a href="#" class="nav-item nav-link text-warning">Hello,  {{user.username}}</a>
                        <a href="{% url 'hope:logout' %}" class="nav-item nav-link text-danger"
                        onclick="return confirm('End your session?')">LOGOUT</a>
                    {% else %}
                        <a href="lib/login" class="nav-item nav-link">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
{% block content %} 

{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

hope/templates/hope/books_by_category.html
{% extends "app.html" %}
    {% block content %}
    <section class="container-fluid mt-3">
        <table class="table table-bordered table-stripped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Copy Number</th>
                    <th>Subject Area</th>
                    <th>Publication Date</th>
                    <th>Status</th>
                    
                </tr>
            </thead>
            <tbody>
                
                {% for book in books %}
                <tr>
                    <td>{{ book.title }}</td>
                    <td>{{ book.author }}</td>
                    <td>{{ book.copy_number }}</td>
                    <td>{{ book.category }}</td>
                    <td>{{ book.publication_date }}</td>
                    <td>
                        {% if book.status == 'AV' %}
                            <a href="{% url 'hope:Borrowpage' book.id %}">Borrow</a>
                        {% else %}  
                            {% if book.status == 'UNAV' %}  
                                <span>Unavailable</span>
                            {% endif %}
                        {% endif %}
                    </td>
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
{% endblock %}

hope/templates/hope/borrow_book.html
  {% extends "app.html" %}
  {% block content %}
    <section class="container-fluid mt-3">
        <section class="row justify-content-center">
            <div class="jumbotron py-1 text-muted">
                Book: {{ book.title }} by {{ book.author }} 
                <hr/>
            </div>
            <div class="col-md-6 mt-2">
                <div class="card card-body shadow">
                    <h5 class="mt-2">Name: {{ book.title }}</h5>
                    <h5 class="mt-2">Author: {{ book.author }}</h5>
                    <h5 class="mt-2">Copy Number: {{ book.copy_number }}</h5>
                    <h5 class="mt-2">Category: {{ book.category }}</h5>
                    <h5 class="mt-2">Date Published: {{ book.publication_date }}</h5>
                    <h5 class="mt-2">Status: Available</h5>
                </div>
            </div> 
            <div class="col-md-6 mt-2">
                <div class="card card-body h-100 shadow">
                    <form action="{% url 'hope:borrow_book' %}" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="book_id" class="form-label d-none">Book ID</label>
                            <input type="hidden" class="form-control" id="book_id" 
                            aria-describedby="bookid" name="book_id" value="{{ book_id }}">
                        </div>
                        <div class="mb-3 text-danger"> 
                            <h5> Note: The book should be picked from the library within 1 hour after booking
                                it. Beyond that, the book will be made available for anyone else to book it.
                            </h5>
                            <p class="text-success">Thank you for understanding. </p>
                        </div>
                        <button type="submit" class="btn btn-primary">Borrow This Book</button>
                      </form>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

hope/templates/hope/borrowed_books.html
{% extends "app.html" %}
    {% block content %}
    <section class="container-fluid mt-3">
        <table class="table table-bordered table-stripped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Copy Number</th>
                    <th>Subject Area</th>
                    <th>Publication Date</th>
                    <th>Status</th>
                    
                </tr>
            </thead>
            <tbody>
                
                {% for book in books %}
                <tr>
                    <td>{{ book.book.title }}</td>
                    <td>{{ book.book.author }}</td>
                    <td>{{ book.book.copy_number }}</td>
                    <td>{{ book.book.category }}</td>
                    <td>{{ book.book.publication_date }}</td>
                    <td>
                        {% if book.book.status == 'AV' %}
                            <a href="{% url 'hope:Borrowpage' book.book.id %}">Borrow Again</a>
                        {% else %}  
                            {% if book.return_status == 'BK' %}
                                Booked (<small> pick it within an hour </small>)
                            {% elif book.return_status == 'RT' %}
                                Returned
                             {% endif %}
                        {% endif %}
                    </td>
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
{% endblock %}

hope/templates/hope/home.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
    <style>
        img {
            width: 1100px;
            height: 600px;
            position: relative;

        }
        body {
            background: url({% static 'hope/media/image.jpg' %});
            background-size:cover;
            background-attachment:fixed;
            }
        ul {
            list-style-type: none;
        }
        li {
            float: left;
        }
        li a {
            display: block;
            color: white;
            padding: 14px 16px;
            background-color: #333;
            text-decoration: none;
            
        }
        li a:hover{
            background-color: green;
        }
        .active {
            background-color: green;
        }
        div {
            float: left;
            text-decoration: none;
            color: white;
        }
        div a {
            float: left;
            text-decoration: none;
            color: white;
        }
    </style>
</head>
<body>
    {% if user.is_authenticated %}
    <div>
        <h3>Hello,  {{user.username}}</h3>
        <a href="lib/logout">LOG OUT</a>
    </div>
    {% else %}
    <ul>
    <li><a href="lib/login">LOGIN</a></li>
    <li><a href="lib/register">REGISTER</a></li>
    </ul>
    {% endif %}
    <!-- <img src="{% static 'lib/media/image.jpg' %}" alt="Background image"> -->
    
    
</body>
</html>

hope/templates/hope/index.html
{% extends "app.html" %}
{% block content %}
    <section class="container-fluid mt-3">
        <table class="table table-bordered table-stripped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Copy Number</th>
                    <th>Subject Area</th>
                    <th>Publication Date</th>
                    <td>Status</td>
                    
                </tr>
            </thead>
            <tbody>
                
                {% for book in books %}
                <tr>
                    <td>{{ book.title }}</td>
                    <td>{{ book.author }}</td>
                    <td>{{ book.copy_number }}</td>
                    <td>{{ book.category }}</td>
                    <td>{{ book.publication_date }}</td>
                    <td>
                        
                        {% if book.status == 'AV' %}
                            <a href="{% url 'hope:Borrowpage' book.id %}">Borrow</a>
                        {% else %}  
                            <!-- {{book.status}}   -->
                            {% if book.status == 'UNAV' %}
                                <span>Unavailable</span>
                            {% endif %}
                        {% endif %}
                    </td>
                   
                        
                </tr>
                    
                {% endfor %}
            </tbody>
        </table>
    </section>
{% endblock %}

hope/templates/hope/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Login page</title>
    <style>
        body, .bg-dk {
            background-color:rgb(19, 36, 42);
           
        }
        p {
            font-weight: bold;
            font-size: 40px;
            text-align: center;
            text-decoration: aquamarine;
            color: aliceblue;
        }
        form {
            text-align: center;
        }
        a {
            text-align: center;
            text-decoration: none;
            font-weight: bold;
        }
        label {
            font-weight: bold;
            color: aliceblue;
        }

    </style>
</head>
<body>
    <ul>
        <!-- <li><a href="About.html">About us</a></li>
        <li><a href="Home.html">Home</a></li> -->
    </ul>
    <br>
    <p>Please login.</p>
    <br>
  
    <form action="{% url 'hope:login' %}" method="POST">
        {% csrf_token %} <!-- required for every post request sent to server-->
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card card-bosy shadow bg-dk">
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="text" name="username" class="form-control" />
                    </div>
                    <div class="form-group">
                         <label for="">Password</label>
                        <input type="password" name="password" class="form-control"/>
                    </div>
                    <div class="mt-3">
                    <input class="btn btn-outline-light w-100" type="Submit" value="Login">
                    </div>
                </div>
                <div class="mt-3">
                    {% for message in messages %}
                        <div class="alert alert-danger">
                            {{message}}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

    </form>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>

hope/templates/hope/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <title>Register</title>
    <style>
        body {
            background-color:rgb(19, 36, 42);
            
        }
        form {
            text-align: center;
        }
        label{
            color: aliceblue;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <form action="{% url 'hope:register' %}" method="POST">
        {% csrf_token %} <!-- required for every post request sent to server-->
        <label for="">Username</label>
        <br>
        <input type="text" name="username" >
        <br>
        <label for="">E-mail</label>
        <br>
        <input type="email" name = "email">
        <br>
        <label for="">First name</label>
        <br>
        <input type="text" name = "first_name" >
        <br>
        <label for="">Last name</label>
        <br>
        <input type="text" name = "last_name">
        <br>
        <label for="">Password</label>
        <br>
        <input type="password" name="password1">
        <br>
        <label for="">Confirm Password</label>
        <br>
        <input type="password" name="password2" >
        <br>
        <input class="btn btn-outline-light w-40" type="submit" value="Register">
        

    </form>
    <div class="mt-3">
        {% for message in messages %}
            <div class="alert alert-danger">
                {{message}}
            </div>
        {% endfor %}
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>